# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
# This example is compatible with Dynamixel using protocol 2.0
Joint1:
  ID: 1
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 170
  Profile_Velocity: 170
Joint2:
  ID: 2
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 170
  Profile_Velocity: 170
Joint3:
  ID: 3
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 170
  Profile_Velocity: 170
Joint4:
  ID: 4
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 170
  Profile_Velocity: 170
Joint5:
  ID: 5
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 170
  Profile_Velocity: 170
Joint6:
  ID: 6
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 170
  Profile_Velocity: 170
Joint7:
  ID: 7
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 170
  Profile_Velocity: 170
Joint8:
  ID: 8
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 170
  Profile_Velocity: 170
Joint9:
  ID: 9
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 170
  Profile_Velocity: 170
Joint10:
  ID: 10
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 170
  Profile_Velocity: 170
Joint11:
  ID: 11
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 170
  Profile_Velocity: 170
Joint12:
  ID: 12
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 170
  Profile_Velocity: 170
Joint13:
  ID: 13
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 170
  Profile_Velocity: 170
Joint14:
  ID: 14
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 170
  Profile_Velocity: 170